---
- name: Create Palworld namespace
  run_once: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: palworld
    state: present

- name: Create RCON secret
  run_once: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: palworld-secrets
        namespace: palworld
      data:
        rconPassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') | b64encode }}"

- name: Deploy Palworld server
  run_once: true
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'files/deployment.yml') }}"
    state: present
    namespace: palworld

- name: Wait for Palworld server to be ready
  run_once: true
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: palworld
    name: palworld-server
  register: palworld_server_info
  until: palworld_server_info.resources[0].status.availableReplicas == 1
  retries: 65
  delay: 10
