---
- name: Create Palworld namespace
  run_once: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: palworld
    state: present

- name: Create RCON secret
  run_once: true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: palworld-secrets
        namespace: palworld
      data:
        rconPassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') | b64encode }}"

- name: Create ConfigMap
  run_once: true
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: palworld-cm-20240102
        namespace: palworld
      data:
        PUID: "1000"
        PGID: "1000"
        PORT: "8211"
        PLAYERS: "16"
        MULTITHREADING: "true"
        RCON_ENABLED: "true"
        RCON_PORT: "25575"
        TZ: UTC
        COMMUNITY: "false"
        SERVER_NAME: "Goon's Palworld"
        SERVER_DESCRIPTION: "Ty is OP"
        ENABLE_INVADER_ENEMY: 'False'
        PAL_EGG_DEFAULT_HATCHING_TIME: '0.000000'
        COLLECTION_DROP_RATE: '1.500000'
        ENEMY_DROP_ITEM_RATE: '1.500000'
        BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: '0.000000'
        DEATH_PENALTY: ItemAndEquipment
        BASE_CAMP_WORKER_MAX_NUM: '25'

- name: Deploy Palworld server
  run_once: true
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'deployment.yml.j2') }}"
    state: present
    namespace: palworld

- name: Wait for Palworld server to be ready
  run_once: true
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: palworld
    name: palworld-server
  register: palworld_server_info
  until: palworld_server_info.resources[0].status.availableReplicas == 1
  retries: 65
  delay: 10
